language: python

os:
  - linux

python:
  - "2.7"
  - "3.6"

matrix:
  include:
    - python: "2.7"
      install:
        - export CFLAGS="-O0"
        - CC=clang python setup.py install
    - python: "3.6"
      install:
        - export CFLAGS="-O0"
        - CC=clang python setup.py install

before_install:
  - pip install coveralls
  - sudo apt-get install -y gdb

install:
  - python setup.py install

before_script:
  - ulimit -c unlimited -S

# command to run tests
script:
  - coverage run --source=iteration_utilities setup.py test

after_success:
  - coveralls

after_failure:
- COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1) # find core file
- if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" example -ex "thread apply all bt" -ex "set pagination 0" -batch; fi
