language: c
os: linux
arch: arm64

jobs:
  include:
  - python: "2.7"
    env:
    - PYVER=python2.7
    - PIPPKG=python-pip
  - python: "3.6"
    env:
    - PYVER=python3.6
    - PIPPKG=python3-pip
  - python: "3.7"
    env:
    - PYVER=python3.7
    - PIPPKG=python3-pip

before_install:
  - sudo apt-get update --yes
  - sudo apt-get install $PYVER $PYVER-dev $PIPPKG --yes
  - $PYVER -m pip install pip setuptools --upgrade

install:
  - $PYVER -m pip install . --no-deps -vv --user

# command to run tests
script:
  - $PYVER -m pip install pytest --user
  - $PYVER -m pytest tests/
